/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package researchstack.backend

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.ConfigurationPropertiesScan
import org.springframework.boot.runApplication

@SpringBootApplication
@ConfigurationPropertiesScan
class HealthResearchBackendApp

fun main(args: Array<String>) {
    runApplication<HealthResearchBackendApp>(*args)
}
