package researchstack.backend.adapter.exception

object ExceptionMessage {
    const val EMPTY_AUTH_CODE = "google authorization code is null or empty"
    const val EMPTY_DASHBOARD_ID = "dashboardId is empty"
    const val EMPTY_CHART_ID = "chartId is empty"
    const val EMPTY_EMAIL = "email is null or empty"
    const val EMPTY_FILEPATH = "filePath is empty"
    const val EMPTY_FILEPATH_LIST = "filePaths is empty"
    const val EMPTY_FIRST_NAME = "firstName is empty"
    const val EMPTY_LAST_NAME = "lastName is empty"
    const val EMPTY_PARTICIPATION_CODE = "participationCode is empty"
    const val EMPTY_PASSWORD = "password is empty"
    const val EMPTY_ROLE = "role is empty"
    const val EMPTY_SENDER = "sender is empty"
    const val EMPTY_SESSION_ID = "sessionId is empty"
    const val EMPTY_STUDY_ID = "studyId is empty"
    const val EMPTY_STUDY_DATA_NAME = "studyData name is empty"
    const val EMPTY_STUDY_DATA_PARENT_ID = "studyData's parentId is empty"
    const val EMPTY_STUDY_NAME = "studyName is empty"
    const val EMPTY_SUBJECT_NUMBER = "subjectNumber is empty"
    const val EMPTY_SUBJECT_NUMBER_LIST = "subjectNumbers is empty"
    const val EMPTY_TASK_ID = "taskId is empty"
    const val EMPTY_TIMESTAMP = "timestamp is empty"
    const val EMPTY_TRIAL_ID = "trialId is empty"
    const val EMPTY_USER_ID = "userId is null or empty"
    const val EMPTY_SUBJECT_ID = "subjectId is null or empty"
    const val EMPTY_INVESTIGATOR_ID = "investigatorId is null or empty"
    const val EMPTY_DATABASE_NAME = "database name is empty"
    const val INVALID_CRON = "cron expression is invalid"
    const val INVALID_SUBJECT_STATUS = "invalid subject status"
    const val INVALID_STUDY_DATA_TYPE = "invalid study data type"
    const val INVALID_STUDY_ASSET_TYPE = "invalid study asset type"
    const val EMPTY_EDUCATION_TITLE = "education title is empty"
    const val EMPTY_EDUCATION_CATEGORY = "education category is empty"
    const val EMPTY_EDUCATIONAL_CONTENT_ID = "educational content id is empty"
    const val EMPTY_IN_LAB_VISIT_PIC_ID = "picId is null or empty"
    const val EMPTY_IN_LAB_VISIT_ID = "in lab visit id is empty"
}
