package researchstack.backend.adapter.outgoing.mongo.repository.healthdata

import researchstack.backend.adapter.outgoing.mongo.entity.healthdata.DeviceStatMobileWearConnectionEntity

interface DeviceStatMobileWearConnectionRepository : HealthDataRepository<DeviceStatMobileWearConnectionEntity>
