package researchstack.backend.adapter.outgoing.mongo.repository.healthdata

import researchstack.backend.adapter.outgoing.mongo.entity.healthdata.DeviceStatWearOffBodyEntity

interface DeviceStatWearOffBodyRepository : HealthDataRepository<DeviceStatWearOffBodyEntity>
