package researchstack.backend.adapter.outgoing.mongo.repository.healthdata

import researchstack.backend.adapter.outgoing.mongo.entity.healthdata.DeviceStatWearPowerOnOffEntity

interface DeviceStatWearPowerOnOffRepository : HealthDataRepository<DeviceStatWearPowerOnOffEntity>
